global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'atlantis-a'
    static_configs:
      - targets: ['atlantis-a:4141']
    metrics_path: '/metrics'

  - job_name: 'atlantis-b'
    static_configs:
      - targets: ['atlantis-b:4141']
    metrics_path: '/metrics'
